### ISSUE TITLE
Install instructions ALTER MAPPING FOR instead of ADD MAPPING FOR

### ISSUE THREAD

**Issue by tpenakov** [quasoft/postgres-tsearch-bulgarian#1]
I've tested the 'How to install' section from README file with postgres:12.1 and on the last statement I've got the following error:
`ERROR:  duplicate key value violates unique constraint "pg_ts_config_map_index"`

It is ok after changing the last line from:

`ALTER TEXT SEARCH CONFIGURATION bulgarian ADD MAPPING FOR asciiword, asciihword, hword, hword_part, word WITH bulgarian_ispell, bulgarian_simple;`

to:
`ALTER TEXT SEARCH CONFIGURATION bulgarian ALTER MAPPING FOR asciiword, asciihword, hword, hword_part, word WITH bulgarian_ispell, bulgarian_simple;`

The similar issue is described [here](https://www.postgresql.org/message-id/4027.1197527793@sss.pgh.pa.us)

Could you please update the README file accorgingly?

**Comment by quasoft** [comment]
Thank you for the feedback!

Fixed
